title       = "uci"
baseURL     = "https://uci-cli.tamnd.com/"
description = "A command line for uci."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/uci-cli"
